version: '3.3'
services:
   db:
     image: mariadb
     volumes:
       - ./dbdata:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
    depends_on:
      - db
    image: wordpress
    ports:
      - 8000:80
      - 443:443
    restart: always
    volumes:
      - ./site:/var/www/html 
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_SERVICE_NAME: sh
    links:
      - db:mysql
# volumes:
#   dbdata: